#############################################################
######    Begin of Makefile
#############################################################

SCADE=C:\Program Files\Esterel Technologies\SCADE R17\SCADE\.

SHELL=cmd.exe

C_FLAGS = -pedantic

all: project2.exe project2.dll 

win32/A661Cosim.o: ../../../../Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/A661Cosim.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\A661Cosim.c" -o "win32\A661Cosim.o"

win32/project2_cosim.o: project2_cosim.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_cosim.c" -o "win32\project2_cosim.o"

win32/project2_UA_2.o: project2_UA_2.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_UA_2.c" -o "win32\project2_UA_2.o"

win32/project2_UA_2_private.o: project2_UA_2_private.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_UA_2_private.c" -o "win32\project2_UA_2_private.o"

win32/project2_UA_2_LAY_1.o: project2_UA_2_LAY_1.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_UA_2_LAY_1.c" -o "win32\project2_UA_2_LAY_1.o"

win32/project2.o: project2.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2.c" -o "win32\project2.o"

win32/kcg_types.o: kcg_types.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "kcg_types.c" -o "win32\kcg_types.o"

win32/kcg_consts.o: kcg_consts.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "kcg_consts.c" -o "win32\kcg_consts.o"

win32/project2_snapshot.o: project2_snapshot.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_snapshot.c" -o "win32\project2_snapshot.o"

win32/project2_type.o: project2_type.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_type.c" -o "win32\project2_type.o"

win32/SmuPredefConv.o: ../../../../Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/C/SmuPredefConv.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\C\SmuPredefConv.c" -o "win32\SmuPredefConv.o"

win32/SmuTypes.o: ../../../../Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/C/SmuTypes.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\C\SmuTypes.c" -o "win32\SmuTypes.o"

win32/SmuLib.o: ../../../../Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/C/SmuLib.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\C\SmuLib.c" -o "win32\SmuLib.o"

win32/SmuVTable.o: ../../../../Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/C/SmuVTable.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\C\SmuVTable.c" -o "win32\SmuVTable.o"

win32/project2_mapping.o: project2_mapping.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_mapping.c" -o "win32\project2_mapping.o"

win32/project2_interface.o: project2_interface.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_interface.c" -o "win32\project2_interface.o"

win32/SmuProxy.o: C:/Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/C/SmuProxy.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "C:\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\C\SmuProxy.c" -o "win32\SmuProxy.o"

project2.dll: win32/A661Cosim.o win32/project2_cosim.o win32/project2_UA_2.o win32/project2_UA_2_private.o win32/project2_UA_2_LAY_1.o win32/project2.o win32/kcg_types.o win32/kcg_consts.o win32/project2_snapshot.o win32/project2_type.o win32/SmuPredefConv.o win32/SmuTypes.o win32/SmuLib.o win32/SmuVTable.o win32/project2_mapping.o win32/project2_interface.o win32/SmuProxy.o SmuExport.def 
	gcc -mwindows -mwin32 -shared -static-libgcc  "win32\A661Cosim.o" "win32\project2_cosim.o" "win32\project2_UA_2.o" "win32\project2_UA_2_private.o" "win32\project2_UA_2_LAY_1.o" "win32\project2.o" "win32\kcg_types.o" "win32\kcg_consts.o" "win32\project2_snapshot.o" "win32\project2_type.o" "win32\SmuPredefConv.o" "win32\SmuTypes.o" "win32\SmuLib.o" "win32\SmuVTable.o" "win32\project2_mapping.o" "win32\project2_interface.o" "win32\SmuProxy.o" -Wl,--output-def,"SmuExport.def" -lm -lwsock32 -m32 -o "project2.dll" 

SmuExport.def: C:/Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/C/SmuExport.def
	copy "C:\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\C\SmuExport.def" "SmuExport.def"

win32/project2_dll.o: project2_dll.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "project2_dll.c" -o "win32\project2_dll.o"

win32/SmuMainWindows.o: C:/Program\ Files/Esterel\ Technologies/SCADE\ R17/SCADE/lib/C/SmuMainWindows.c
	gcc -I"." -I"$(SCADE)" -I"$(SCADE)\include" -I"$(SCADE)\include\C" -I"$(SCADE)\include\Ada" -I"$(SCADE)\lib\Ada" -I"..\..\..\..\Program Files\Esterel Technologies\SCADE R17\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DEXTENDED_SIM -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c -ansi -std=c99 -m32 "C:\Program Files\Esterel Technologies\SCADE R17\SCADE\lib\C\SmuMainWindows.c" -o "win32\SmuMainWindows.o"

project2.exe: win32/project2_dll.o win32/SmuMainWindows.o 
	gcc "win32\project2_dll.o" "win32\SmuMainWindows.o" -lm -lwsock32 -m32 -o "project2.exe" 

project2_cosim.c: project2_UA_2.h


#############################################################
######    End of Makefile
#############################################################
