/*********************************************************
 **
 ** File  Main_UA_1_LAY_1.c
 **
 ** Automatically generated by SCADE Suite UA Adaptor
 ** Version 2019 R2a (build 20190702)
 ** 
 ** Date of generation: 2019-09-29T23:27:00
 ** Command line: C:/Program Files/ANSYS Inc/v194/SCADE/SCADE/bin/uaadaptor.exe -sdy C:\Repositorio_ITA\SCADE\ExLab2\FuelManagement\FuelManagement.sdy -n C:\Program Files\ANSYS Inc\v194\SCADE\SCADE Display\config\a661_description\a661.xml -outdir C:/Repositorio_ITA/SCADE/ExLab2/FuelManagement/Simulation -k C:/Repositorio_ITA/SCADE/ExLab2/FuelManagement/Simulation/kcg_trace.xml -o Main_UA_1 -i FuelManagement_interface.h -encoding UTF-8 C:\Repositorio_ITA\SCADE\ExLab2\Fuel_tank\FM.sgfx
 *********************************************************/
#include "kcg_sensors.h"
#include "Main_UA_1.h"
#include "Main_UA_1_constants.h"
#include "Main_UA_1_private.h"

/* Perform UA Request for layer 1 */
A661_INTERNAL uaa_size a661_com_A661_CMD_UA_REQUEST_layer_1(buffer_el msg[], 
  outC_Main* scade_ctx,  extern_out_ctx_t * extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->LayerVisible){
    
    if (scade_ctx->LayerVisible){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_8(msg + offset,
        A661_REQ_LAYER_VISIBLE, 0);
    }
  }
  return offset ;
}

/* Pack messages for layer 1 */
 uaa_size a661_com_layer_1(buffer_el msg[], 
  outC_Main* scade_ctx,  extern_out_ctx_t* extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->FuelColor.Emit ||
  scade_ctx->FuelLevel.Emit ||
  scade_ctx->FuelVisible.Emit ||
  scade_ctx->TankFullVisible.Emit ||
  scade_ctx->RefuelEnable.Emit ||
  scade_ctx->FuelTypeEnable.Emit ||
  scade_ctx->LayerVisible){
    LAYER("a661_layer#1");
    offset = 8;
    a661_msg_cmd_header(msg, 1, Main_UA_1_DEFAULT_CONTEXT_NUMBER);
    if (scade_ctx->FuelColor.Emit ||
    scade_ctx->FuelLevel.Emit ||
    scade_ctx->FuelVisible.Emit){
      WIDGET("GprFuel#3");
      offset = offset + a661_com_csp_widget_GpRectangle(msg + offset, 3,
        scade_ctx->FuelColor.Emit, scade_ctx->FuelColor.Value,
        scade_ctx->FuelColor.Emit, scade_ctx->FuelColor.Value,
        scade_ctx->FuelLevel.Emit, scade_ctx->FuelLevel.Value,
        scade_ctx->FuelVisible.Emit, scade_ctx->FuelVisible.Value);
    }
    if (scade_ctx->TankFullVisible.Emit){
      WIDGET("BcTankFull#6");
      offset = offset + a661_com_csp_widget_BlinkingContainer(msg + offset, 6,
        scade_ctx->TankFullVisible.Emit, scade_ctx->TankFullVisible.Value);
    }
    if (scade_ctx->RefuelEnable.Emit){
      WIDGET("PbRefuel#8");
      offset = offset + a661_com_csp_widget_PushButton(msg + offset, 8,
        scade_ctx->RefuelEnable.Emit, scade_ctx->RefuelEnable.Value);
    }
    if (scade_ctx->FuelTypeEnable.Emit){
      WIDGET("CbFuelType#10");
      offset = offset + a661_com_csp_widget_ComboBox(msg + offset, 10,
        scade_ctx->FuelTypeEnable.Emit, scade_ctx->FuelTypeEnable.Value);
    }
    if (scade_ctx->LayerVisible){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_layer_1(msg + offset,
        scade_ctx, extern_ctx);
    }
    WRITE_ULONG(msg + offset, A661_END_BLOCK);
    offset = offset + 4;
    WRITE_ULONG(msg + 4, offset);
  }
  return offset ;
}

/*********************************************************
 ** End of file
 ** End of generation: 2019-09-29T23:27:00
 *********************************************************/

